apiVersion: v1
kind: Config
current-context: ${cluster_name}
clusters:
- name: ${cluster_name}
  cluster:
    certificate-authority-data: ${cluster_certificate_authority_data}
    server: ${cluster_endpoint}
contexts:
- name: ${cluster_name}
  context:
    cluster: ${cluster_name}
    user: ${cluster_name}
users:
- name: ${cluster_name}
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ${aws_region}
      - eks
      - get-token
      - --cluster-name
      - ${cluster_name}
      command: aws
      env:
      - name: AWS_PROFILE
        value: ${aws_profile}